### ISSUE TITLE
stns.conf が存在しないと Kernel panic

### ISSUE THREAD

**Issue by levkkuro** [STNS/libnss#11]
/etc/stns/client/stns.conf が存在しないと
OS起動時に、Kernel panic となることを確認しました。

環境は、EC2インスタンスで、OSは Amazon Linux (4.14.94-73.73.amzn1.x86_64)
libnss-stns-v2.x86_64 は 2.2.3-1 です。
```
init: stns_load_config(stns)[L65] cannot open /etc/stns/client/stns.conf: No such file or directory

[    3.088145] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    3.088145] 
```

**Comment by pyama86** [comment]
状況的にかなり稀なケースになると思うので、すごく暇な時に対応します〜

**Comment by pyama86** [comment]
https://github.com/STNS/libnss/blob/master/stns.c#L67
このあたりで安直にexit 1で殺してるから、だめな実装ですね。戻り値とってNSS_UNAVAILABLEを返すようにしますね。

**Comment by pyama86** [comment]
https://github.com/STNS/libnss/pull/13
対応しました〜
