### ISSUE TITLE
TLSクライアント認証有効時のディレクトリ権限

### ISSUE THREAD

**Issue by levkkuro** [STNS/libnss#12]
https://github.com/STNS/STNS/issues/67#issuecomment-469169760
の件ですが、以前のバージョンから発生することを確認しました(そのため一部文言を修正しました)。

TLSクライアント認証有効時にSTNSサーバーへ問い合わせが発生する際には、/etc/stns/keys/ ディレクトリに その他ユーザーの実行権限が必要となることを確認しました。
その他ユーザーに実行権限があると、ディレクトリ内のファイルフルパスを知っている場合にcatなどでのぞけてしまうため、できれば権限を絞りたいです。

### 確認した環境
```
EC2インスタンス(4.9.32-15.41.amzn1.x86_64)
libnss-stns.x86_64    0.4-1
libpam-stns.x86_64    0.4-1
```
```
EC2インスタンス(4.14.94-73.73.amzn1.x86_64)
libnss-stns-v2.x86_64 2.2.3-1
libpam-stns.x86_64    0.4.5-1
```

#### 発生する

```
drwxr-xr-- 3 root root XXXX  X月 XX XX:XX /etc/stns/keys/
```

 #### 発生しない

```
drwxr-xr-x 3 root root XXXX  X月 XX XX:XX /etc/stns/keys/
```
```
drwxr-x--x 3 root root XXXX  X月 XX XX:XX /etc/stns/keys/
```
### 事象
```
$ ssh <ログイン先サーバーIP> -l <ユーザー名>
〜
id: cannot find name for user ID XXXXX
id: グループ ID XXXXX のグループ名がみつかりません
id: cannot find name for user ID XXXXX
-bash-4.2$
-bash-4.2$ id
uid=XXXXX gid=XXXXX groups=XXXXX ←各IDのみの出力となる
```

### 再現方法
* libnss-stns.x86_64    0.4-1
```
nscd→STNSサーバー という順に参照するため、
以下nscdのキャッシュを削除し、
# nscd -i passwd
# nscd -i group
STNSサーバーに登録されたユーザーで以下を実行する
$ id 
```
* libnss-stns-v2.x86_64 2.2.3-1
```
/var/cache/stns(cache = false の場合はスキップ)→nscd→STNSサーバー
という順に参照するため、
cache = false に設定し(念の為/var/cache/stns以下も削除)、
以下nscdのキャッシュを削除し、
# nscd -i passwd
# nscd -i group
STNSサーバーに登録されたユーザーで以下を実行する
$ id 
```

### id実行時のstrace抜粋
/etc/stns/keys/ ディレクトリ にその他ユーザーの実行権限がない、かつ キャッシュが存在しない場合、idコマンドのstraceで以下が出力されます。
```
15:04:18.065046 open("/etc/stns/keys/client.crt", O_RDONLY) = -1 EACCES (Permission denied) <0.000009>
```

### 備考
libnss-stns-v2.x86_64 2.2.3-1 ではnscdが不要になったとのことですが、参照はしていることを確認しました。以下はnscd をstopしているときにidを実行した時のstrace抜粋です。
```
15:03:34.603201 connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory) <0.000011>
```

**Comment by pyama86** [comment]
名前解決自体はユーザー権限で行われるので、それはそうなるかなぁと言う印象を受けました。setuidすれば行けそうな気もしますが、これは逆に特権をもたせることになるのでセキュリティ面から望ましくないかなと思っています。

備考の件については、Linuxの挙動なような気がします。(特にSTNSがnscdを意識しているわけではない)

**Comment by yteraoka** [comment]
鍵を守りたいだけなら proxy を立てれば良さそうです。サーバー内から STNS サーバーとの通信をさせないというのは無理そう。
で、ふと気が付いたのですが STNS サーバーが返すパスワードってそのまま見えちゃいますね。私は公開鍵認証用途しか考えていなかったので調べてないのですが、ここには /etc/shadow のような hash を入れておくのでしょうか？それでも見えてしまうのはあまりよろしくないですね。

**Comment by pyama86** [comment]
> で、ふと気が付いたのですが STNS サーバーが返すパスワードってそのまま見えちゃいますね。私は公開鍵認証用途しか考えていなかったので調べてないのですが、ここには /etc/shadow のような hash を入れておくのでしょうか？それでも見えてしまうのはあまりよろしくないですね。

hashを入れることを想定しています。
https://github.com/STNS/stns-passwd

僕自身もパスワード認証を全く使ってないので、方向性としてはetcdなどでバックエンド持ちつつ、oAuthとかがいいかなと思っています。

**Comment by levkkuro** [comment]
お二人ともアドバイスありがとうございました。
(備考の件は、あくまでidの実行結果であり(idが名前解決のためにnscdキャッシュをみにいっているだけ)、STNSとは切り離して考えるべきでした、失礼致しました)
本件、クローズさせていただきます。
