### ISSUE TITLE
stns-key-wrapper: inner_http_request(stns)[L303] http request failed: No error

### ISSUE THREAD

**Issue by buty4649** [STNS/libnss#24]
Hi! @pyama86 

STNS上に存在しないユーザをstns-key-wrapperに渡すと、以下のようなログがsyslogに出力されます(`***` はサーバ名なのでマスクします)。

```
Aug 20 15:41:36 *** stns-key-wrapper: inner_http_request(stns)[L303] http request failed: No error
```

`No error` の通り運用上は問題ないのですが、syslogがこのログで埋まってしまったりと大変なので対処いただけたら助かります！

## 再現環境

```
$ rpm -qa | grep stns
libnss-stns-v2-2.3.3-2.x86_64
```

## 再現方法

```
$ /usr/lib/stns/stns-key-wrapper unknown-user
http request failed user: unknown-user
$ sudo tail -1 /var/log/messages
Aug 20 15:44:40 *** stns-key-wrapper: inner_http_request(stns)[L303] http request failed: No error
```

**Comment by pyama86** [comment]
どもども〜
対応しておきます！

**Comment by pyama86** [comment]
か、もしくは興味があればパッチ書いてもらっても・・・。
だいたいmake testとかで動作確認できるようになってる。

**Comment by pyama86** [comment]
`make docker` `make test`　か。

**Comment by hiboma** [comment]
下記のコードで `code == 404` の時にログを出さないようにするといいのかな? 

https://github.com/STNS/libnss/blob/d76d1dd5b429a583f91efe4c94a16b4eccd3bee5/stns.c#L301-L308

**Comment by pyama86** [comment]
良さそうです。ついでにログにコード出すと今後類似の切り分け早くなりそうですね。
