### ISSUE TITLE
stns.conf の CA証明書パス指定

### ISSUE THREAD

**Issue by levkkuro** [STNS/libnss#25]
libnss-v2 では 設定ファイル(stns.conf)の [tls]から
CA証明書のパス指定(ca = )がなくなっていると認識しています。
https://stns.jp/en/configuration

stns.conf で `ssl_verify = true` にすると、
`/etc/pki/tls/certs/ca-bundle.crt` を参照しに行きます。
そのため、CA証明書の パス指定を復活していただきたいです。
(現状は、ca-bundle.crt に CA証明書 を追記して動作させています)

**Comment by pyama86** [comment]
isucon諸々終わったらやりますね〜

**Comment by levkkuro** [comment]
以下をインストールしたのですが、なぜか修正が反映されていないようで、
ca = "/etc/stns/XXXX/cacert.pem" と指定しても
/etc/pki/tls/certs/ca-bundle.crt を参照しにいくようです。
https://github.com/STNS/libnss/releases/download/v2.4.1/libnss-stns-v2-2.4.1-1.x86_64.el6.rpm

- 確認方法
上記 crt ファイルを退避すると、/var/log/messages に以下ログが出力されることから、
/etc/pki/tls/certs/ca-bundle.crt を参照していることが分かる
```
stns-key-wrapper: inner_http_request(stns)[L310] http request failed: Problem with the SSL CA cert (path? access rights?) code:0
```

ちなみに、最新 source から make pkg で作成した rpmでは、
ca = "/etc/stns/XXXX/cacert.pem" の指定通りとなりました。

**Comment by pyama86** [comment]
ぎゃ・・・
```

% git pull origin master
From github.com:STNS/libnss
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 stns.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```
pullしてなかったです・・・

**Comment by pyama86** [comment]
再リリースしました！

**Comment by levkkuro** [comment]
以下をインストールし、ca = "/etc/stns/XXXX/cacert.pem" の指定通りとなることを確認しました！
```
# yum install https://github.com/STNS/libnss/releases/download/v2.4.1/libnss-stns-v2-2.4.1-1.x86_64.el6.rpm
```

**Comment by pyama86** [comment]
諸々ありがとうございました！
