### ISSUE TITLE
cache-stnsdのリリースについて

### ISSUE THREAD

**Issue by pyama86** [STNS/libnss#37]
https://ten-snapon.com/archives/2418

上記のブログを公開したところ、@fujiwawa さんから[フィードバック](https://twitter.com/fujiwara/status/1282930750430445568?s=20)があり、それを踏まえて、下記のようにしようかなと考えています。
現在ご利用の方で運用上困るとかそういったご意見があれば教えて下さい。

1. libnss-stns-v2のdependsにcache-stnsdを追加
2. `/etc/stns/client/stns.conf`に下記の設定を入れない限りは既存の動作を継続
```toml
use_cached = true
```
上記を入れた場合は、unix domain socketを通じてcache-stnsdと通信し、cache-stnsdを通じてすべてのクエリをサーバに発行します。

3. libnss-stns-v2の2.9 or libnss-stns-v3において、`use_cached = true` をデフォルトにする

**Comment by fujiwara** [comment]
検討ありがとうございます。

> libnss-stns-v2の2.9 or libnss-stns-v3において、use_cached = true をデフォルトにする

cachedを別に置くことでlibnss-stns自体の実装をコンパクトに出来るのが利点だと思いますので、

- v2.9 では移行措置として use_cached = true がない場合はこれまで通り内部の cache を使用する
- v3 では cached を必須にし、v2 互換の内部 cache は削除

という形でもよいかと思います。

v2 で運用中のホストで新しいパッケージをインストールすると突然動作しない、という事態は避けたいですが、パッケージが分かれている v3 であれば問題ないかと。

**Comment by pyama86** [comment]
そうですね。懸念されている点は、rpmやdebの自動起動の作り込みで突然動作しないというのは避けられそうではありますが、結局運用者としてはcache-stnsdのプロセス監視を入れたり、やるとことが増えるので、パッケージのレイヤーで明示的に意思決定できるようにしたほうが良さそうですね。
頂いた案でドキュメントサイトなどにも取り入れたいと思います！フィードバックありがとうございます！

**Comment by pyama86** [comment]
完全にリリースした。
