### ISSUE TITLE
can not install libnss-stns-v2 in Ubuntu 20.04

### ISSUE THREAD

**Issue by paihu** [STNS/libnss#41]
Unable to install libnss-stns-v2 in Ubuntu 20.04 after changing apt repository URL

* before repo url https://repo.stns.jp/debian stns main
* after repo url https://repo.stns.jp/${DIST} stns ${DIST}

now 
execute
```
curl -fsSL https://repo.stns.jp/scripts/apt-repo.sh | sh
```
and following error
```
''https://repo.stns.jp/focal stns Release'' does not have a Release file
```

**Comment by pyama86** [comment]
probably I resolve  your trouble reason.
could you please try this command.

```
$ sudo apt install ca-certificates
```

refs: https://www.walbrix.co.jp/article/openssl-102-letsencrypt-crisis.html

**Comment by paihu** [comment]
thanks quick feedback.

```
curl https://repo.stns.jp/focal/dists/stns/InRelease 
```
the command return contents.

but apt update fail, because ca-certificate was old.
after `apt-get install ca-certificates`, apt update succeeded.

**Comment by pyama86** [comment]
I was faster because of the difference in touch!
Have a nice weekend!
