### ISSUE TITLE
When will the version with Nobel support be released

### ISSUE THREAD

**Issue by salmon111** [STNS/libnss#93]
Thank you for addressing the issue at https://github.com/STNS/STNS/issues/269.

I noticed that there is still an error occurring at https://github.com/STNS/package/actions/runs/8812436612/job/24188124397#step:5:1464 
because the builds/libnss*64*noble*.deb has not been released yet.

Please let me know if there's a confirmed release date.

**Comment by pyama86** [comment]
https://github.com/STNS/libnss/actions/runs/8827347592/job/24234483114
Please wait for a while as it is currently being built. Cross-builds take quite some time.

**Comment by pyama86** [comment]
It took a lot of time, but I was able to release it successfully. Please check it.
https://github.com/STNS/package/actions/runs/8812436612/job/24324692708#step:5:1969

**Comment by salmon111** [comment]
Thank Youuuuuuu!!!!!🚀
