### ISSUE TITLE
add support for debian 12

### ISSUE THREAD

**Issue by Quesys-tech** [STNS/libnss#96]
はじめまして

現在、libnssが最新版のDebian 12 (Bookworm)ではaptによるインストールができない状況にあります。

問題点:
1. 現在のパッケージがDebian 12に対応したビルドがない

提案:
1. Debian 12環境でのビルドとテストの実施

このサポート追加作業には、私も積極的に取り組みたいと考えています。
ご検討いただけますと幸いです。何か質問や追加情報が必要な場合は、お知らせください。

**Comment by pyama86** [comment]
issueありがとうございます。
ピッとやっていきます。

**Comment by pyama86** [comment]
対応完了しました！

**Comment by Quesys-tech** [comment]
迅速に対応してくださりありがとうございます！
